version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  darko-master:
    image: darko:latest
    env_file:
      - master.env
    ports:
    - "8888:8888"
    depends_on:
      - redis

  darko-follower-0:
    image: darko:latest
    env_file:
      - follower.env
    environment:
      - DARKO_RATE_LIMIT_SHARD=0
    depends_on:
      - redis

  darko-follower-1:
    image: darko:latest
    env_file:
      - follower.env
    environment:
      - DARKO_RATE_LIMIT_SHARD=1
    depends_on:
      - redis

  darko-follower-2:
    image: darko:latest
    env_file:
      - follower.env
    environment:
      - DARKO_RATE_LIMIT_SHARD=2
    depends_on:
      - redis
